additionalRepositories: 
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: islandora-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: dspace-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: oulib-remote

tasks: 
  - name: OULib remote worker
    before: | 
      cd ../oulib-remote
    init: |
      echo "doing init"
    command: |
      git status
      echo "doing command"


# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
    visibility: private
  - port: 443
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 27017
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
