additionalRepositories: 
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: islandora-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: dspace-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: oulib-remote

tasks:
  - name: cyberCommons
    before: cp dc_config/secrets_template.env dc_config/secrets.env
    init: |
      make init &&
      make build &&
      make collectstatic &&
      gp sync-done cyber # 'cyber' is arbitrary name
    command: make run 
    
  - name: Islandora remote worker
    before: | 
      cd ../islandora-remote &&
      git checkout islandoraq
    init: |
      gp sync-await cyber  #  wait for the above 'init' to finish
      make init
    command: make run

  - name: Dspace remote worker
    before: | 
      cd ../dspace-remote &&
      git checkout dspaceq
    init: |
      gp sync-await cyber  #  wait for the above 'init' to finish
      make init
    command: make run

  - name: OULib remote worker
    before: | 
      cd ../oulib-remote &&
      git checkout oulibq
    init: |
      gp sync-await cyber  #  wait for the above 'init' to finish
      make init
    command: make run

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
    visibility: private
  - port: 443
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 27017
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
