# The celery-remote-worker repo contains config for deploying remote worker 
# code to a gitpod environment along with cybercommons for dev/test work. 
additionalRepositories: 
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: islandora-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: dspace-remote
  - url: https://github.com/oulib-datacatalog/celery-remote-worker
    checkoutLocation: oulib-remote
workspaceLocation: cybercommons/cybercommons.code-workspace


tasks:
  - name: cyberCommons
    before: cp dc_config/secrets_template.env dc_config/secrets.env
    init: >
      make init &&
      make build &&
      make collectstatic &&
      gp sync-done cyber
    command: make run 
    
  - name: Islandora remote worker
    before: | 
      cd ../islandora-remote
      git remote set-branches origin 'islandoraq'
      git fetch
      git checkout islandoraq
    init: |
      gp sync-await cyber && make init
    command: make run

  - name: Dspace remote worker
    before: | 
      cd ../dspace-remote
      git remote set-branches origin 'dspaceq'
      git fetch
      git checkout dspaceq
    init: |
      gp sync-await cyber && make init
    command: make run

  - name: OULib remote worker
    before: | 
      cd ../oulib-remote
      git remote set-branches origin 'oulibq'
      git fetch
      git checkout oulibq
    init: |
      gp sync-await cyber && make init
    command: make run

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
    visibility: private
  - port: 443
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 27017
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
