#!/usr/bin/env python3

import os
from subprocess import run  # nosec

for itm in os.environ.get("CELERY_SOURCE").split(","):
    run(["/usr/local/bin/python", "-m", "pip", "install", itm], shell=False, check=True)  # nosec

celery_queue = os.environ.get("CELERY_QUEUE", "celery")
log_level = os.environ.get("LOG_LEVEL", "INFO")

run(["/usr/local/bin/celery", "worker", "-Q", celery_queue, "-l", log_level], shell=False, check=True)  # nosec
